name: ✨ Feature Request
description: Suggest a new feature for CodeMate Studio
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see
      placeholder: What would you like to add or improve?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation & Use Case
      description: Why would this feature be useful? What problem does it solve?
      placeholder: Describe the problem or opportunity this addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this working?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: dropdown
    id: phase
    attributes:
      label: Relevant Phase
      description: Which phase would this feature belong to?
      options:
        - "Core Application"
        - "Phase 1: Infrastructure"
        - "Phase 2: Supabase Backend"
        - "Phase 3: API Security"
        - "Phase 4: CI/CD"
        - "Phase 5: Deployments"
        - "Phase 6: PWA"
        - "Phase 7: Mobile"
        - "Phase 8: Store Readiness"
        - "Phase 9: AI Workflows"
        - "Phase 10: Templates"
        - "Phase 11: Observability"
        - "Phase 12: Enterprise"
        - "New Phase Needed"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "Low - Nice to have"
        - "Medium - Would improve experience"
        - "High - Important for adoption"
        - "Critical - Blocking major use case"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other details, mockups, or examples that would help