// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbclknkdwpyjaxaaknxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiY2xrbmtkd3B5amF4YWFrbnhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMDM0NTQsImV4cCI6MjA3NDc3OTQ1NH0.My4c3b2pgYtO-zV0z8NBG6PZWIpWZgdk3kNU6LTl7Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});